Feature/15534787 date calc para
chapter-three/jcc-srl pull request #141
Opened 2019-12-03 21:47 UTC by zakiya

CI comment is missing for some reason.
https://pr-141-jcc-srl.pantheonsite.io/service

Notes: 
(1) The wayfinder node is currently using node.html.twig so it's rendering paragraphs inside the text component which will cause multiple datefinders on a page to act erratically. I figure that will be fixed when that content type is themed, so I didn't work on that node template in this PR. Should work fine once {{ content }} is placed outside of that component.

(2) I imported the flatfindr files using advice [here](https://laravel.com/docs/6.x/mix#working-with-stylesheets). Let me know if there's a different/better way to do it.

2019-12-05 16:12 UTC, jacine requested changes
This is so nice to see!  👏 

Left some feedback @zakiya.

2019-12-05 16:12 UTC, jacine commented on web/themes/custom/atrium/webpack.mix.js
> +
Good idea. 👍

2019-12-05 16:12 UTC, jacine commented on web/themes/custom/atrium/src/js/datefinder.js
> +(function ($) {
Instead of manually listing the file in the mix config, you just need to do the following at the top of this file (before the closures), and Webpack will handle the rest/

```js
import flatpickr from 'flatpickr';
```

2019-12-05 16:12 UTC, jacine commented on web/themes/custom/atrium/src/js/datefinder.js
> +        }
Nitpick...  when you remove the date, the old result text stays.  Maybe add an else to reset it?

```js
else {
  $(idStr + resultContainerSelector).attr('hidden', true);
  $(idStr + resultTextSelector).html('');
}
```

2019-12-05 16:37 UTC, zakiya commented on web/themes/custom/atrium/src/js/datefinder.js
> +(function ($) {
Ah. I tried to include it after the enclosures. Very cool.

2019-12-05 16:37 UTC, zakiya commented on web/themes/custom/atrium/src/js/datefinder.js
> +        }
Good note.

2019-12-05 20:25 UTC, jacine commented on composer.json
> +        "exygy/courtyard": "dev-development#49d139",
@zakiya Note: this will need to be updated to: `034afec` which i have in #142, if you happened to merge that first.

2019-12-05 20:26 UTC, jacine commented
@zakiya I know you are busy... if you want me to make the changes I requested here, just lmk! 😄

2019-12-06 01:06 UTC, zakiya commented
@jacine JUST seeing your last comment now. Meetings, meetings, meetings. Once CI is finished, this _should_ be ready for review again.

2019-12-06 03:35 UTC, jacine commented on composer.json
> +        "exygy/courtyard": "dev-development#49d139",
This is the last thing... I will fix this part and merge in the morning 👍😁

2019-12-06 13:43 UTC, jacine approved these changes

2019-12-06 13:43 UTC, merged